### PR TITLE
Adds new zip-code validation format for Ireland

### PR DESCRIPTION
**Pull request by nigobo**
Fixes issue with A98F625 not validating correctly

### CODE REVIEW

**Comment by BenMorel** [comment]
Hi, can you add this postcode to the [tests](https://github.com/brick/postcode/blob/35ec0cffda37e92a351c6aebd5fde33244d31144/tests/Formatter/IEFormatterTest.php#L48-L54)?

**Comment by BenMorel** [comment]
Thanks! By the way, as a side effect this change accepts postcodes in format `ANW ANNN` as well, is this format valid?

**Comment by nigobo** [comment]
As I understand it it looks ok. [Eircode](https://www.eircode.ie/docs/default-source/Common/prepareyourbusinessforeircode-edition3published.pdf?sfvrsn=2)

Screenshot 2021-02-22 at 14 43 04

**Comment by BenMorel** [comment]
Thank you. Released as [0.2.5](https://github.com/brick/postcode/releases/tag/0.2.5)!

**Pull request merged**
