### PR TITLE
Add additional character to GBFormatter alphaIn

### PR DESCRIPTION
**Pull request by chris-ware**
This adds support for postcodes ending in a C such as TQ12 6QC which is a valid postcode: https://www.devon.gov.uk/communities/assets/stover-country-park

### CODE REVIEW

**Comment by BenMorel** [comment]
Hi, thank you for your PR! Please add a test [here](https://github.com/brick/postcode/blob/master/tests/Formatter/GBFormatterTest.php) and I'll merge it.

**Comment by chris-ware** [comment]
@BenMorel Hopefully I've done as requested, tests now pass instead of failing where they were testing agains C being in the inwards code.

**Comment by BenMorel** [comment]
Thank you, just one thing: can the `C` only be at the end? Or anywhere in the inward code?

**Comment by chris-ware** [comment]
@BenMorel I believe the C can be in any position in the inward code

**Comment by BenMorel** [comment]
Thank you! Released as [0.2.7](https://github.com/brick/postcode/releases/tag/0.2.7)

**Pull request merged**
